#ifndef _CS_PALETTE_H_
#define _CS_PALETTE_H_

enum PALETTE_NUM : unsigned char
{
	PALETTENUM_1 = 0,
	PALETTENUM_2,
	PALETTENUM_3,
	PALETTENUM_4,
	PALETTENUM_5,

	PALETTENUM_MAX
};

enum PALETTE_SLOT : unsigned char
{
	PALETTESLOT_1 = 0,
	PALETTESLOT_2,
	PALETTESLOT_3,
	PALETTESLOT_4,
	PALETTESLOT_5,
	PALETTESLOT_6,
	PALETTESLOT_7,
	PALETTESLOT_8,
	PALETTESLOT_9,
	PALETTESLOT_0,
	PALETTESLOT_31,
	PALETTESLOT_32,
	PALETTESLOT_33,
	PALETTESLOT_34,
	PALETTESLOT_35,
	PALETTESLOT_36,
	PALETTESLOT_37,
	PALETTESLOT_38,
	PALETTESLOT_39,
	PALETTESLOT_40,
	PALETTESLOT_41,
	PALETTESLOT_42,
	PALETTESLOT_43,
	PALETTESLOT_44,
	PALETTESLOT_45,
	PALETTESLOT_46,
	PALETTESLOT_47,
	PALETTESLOT_48,
	PALETTESLOT_49,
	PALETTESLOT_MAX
};

enum PALETTE_ITEM_TYPE : unsigned char
{
	PIT_NONE = 0,

	PIT_ITEM,
	PIT_TALENT,

	PIT_MAX
};

#endif